# Generated by Django 5.1.2 on 2024-11-01 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
