# Generated by Django 5.1.2 on 2024-11-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_for',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
